#
# API Priority and Fairness
#
# watch -n 1 'kubectl get --raw /debug/api_priority_and_fairness/dump_priority_levels'
#
# watch -n 1 'kubectl get --raw /debug/api_priority_and_fairness/dump_requests'
#
# kubectl get --raw /debug/api_priority_and_fairness/dump_queues
#
# In this one, look for the "dispatched_requests_total":
# watch -n 0.5 "kubectl get --raw /metrics | grep 'flow_schema=\"nnf-nlc\"' | head -n 6"
#
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  name: nnf-clientmount
spec:
  limited:
    lendablePercent: 10
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 128
      type: Queue
    nominalConcurrencyShares: 100
  type: Limited
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: nnf-clientmount
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 8000
  priorityLevelConfiguration:
    name: nnf-clientmount
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
      - kind: ServiceAccount
        serviceAccount:
          name: nnf-clientmount
          namespace: nnf-system
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  name: nnf-nlc
spec:
  limited:
    lendablePercent: 90
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 128
      type: Queue
    nominalConcurrencyShares: 100
  type: Limited
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: nnf-nlc
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 8001
  priorityLevelConfiguration:
    name: nnf-nlc
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
      - kind: ServiceAccount
        serviceAccount:
          name: nnf-node-controller
          namespace: nnf-system
      - kind: ServiceAccount
        serviceAccount:
          name: nnf-dm-node-controller
          namespace: nnf-dm-system
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  name: nnf-dm-daemon
spec:
  limited:
    lendablePercent: 90
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 50
      type: Queue
    nominalConcurrencyShares: 5
  type: Limited
---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: nnf-dm-daemon
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 8003
  priorityLevelConfiguration:
    name: nnf-dm-daemon
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
      - kind: ServiceAccount
        serviceAccount:
          name: nnf-dm-daemon
          namespace: nnf-dm-system
