---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- lustre-fs-operator-crds.yaml
- lustre-fs-operator.yaml
#- lustre-fs-operator-prometheus.yaml

components:
- ../../universal/container-locations
