---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nnf-sos-crds.yaml
- nnf-sos.yaml
- nnf-sos-examples.yaml
- systemconfiguration.yaml
#- nnf-sos-prometheus.yaml

components:
- ../components/container-locations
- ../../universal/container-locations
