---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nnf-sos-crds.yaml
- nnf-sos.yaml
- nnf-sos-examples.yaml
- nnf-sos-ports.yaml
#- nnf-sos-prometheus.yaml

# The following are cluster-specific and are not touched by unpack-manifest.
- systemconfiguration.yaml
- default-nnfstorageprofile.yaml
- default-nnfdatamovementprofile.yaml
- lvmlockd-profiles.yaml

components:
- ../components/container-locations
- ../../universal/container-locations
