---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: alpine
  newName: alpine
  #newName: quay.io.co/gitlab/alpine
  #newTag: "3.19"

- name: busybox
  newName: busybox
  #newName: quay.io.co/gitlab/busybox
  #newTag: 1.34.1

- name: quay.io/jetstack/cert-manager-cainjector
  newName: quay.io/jetstack/cert-manager-cainjector
  #newName: quay.io.co/gitlab/cert-manager-cainjector
- name: quay.io/jetstack/cert-manager-controller
  newName: quay.io/jetstack/cert-manager-controller
  #newName: quay.io.co/gitlab/cert-manager-controller
- name: quay.io/jetstack/cert-manager-webhook
  newName: quay.io/jetstack/cert-manager-webhook
  #newName: quay.io.co/gitlab/cert-manager-webhook

- name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newName: registry.k8s.io/sig-storage/csi-node-driver-registrar
  #newName: quay.io.co/gitlab/csi-node-driver-registrar

- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: gcr.io/kubebuilder/kube-rbac-proxy
  #newName: quay.io.co/gitlab/kube-rbac-proxy
  #newTag: v0.14.1

- name: mpioperator/mpi-operator
  newName: mpioperator/mpi-operator
  #newName: quay.io.co/gitlab/mpi-operator
