---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- systemconfiguration.yaml
- mgt-pool-member-nnfstorageprofile.yaml
- lvmlock-systemstorage.yaml

patches:
- target:
    kind: SystemConfiguration
    name: default
    namespace: default
  patch: |-
    kind: SystemConfiguration
    metadata:
      name: default
      annotations:
        # ServerSideApply because on some systems this resource can be quite large.
        # Replace to let this resource avoid the conversion webhook.
        argocd.argoproj.io/sync-options: ServerSideApply=true,Replace=true

