---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dws-crds.yaml
- dws.yaml
#- dws-prometheus.yaml

components:
- ../../universal/container-locations

patches:
- target:
    kind: Deployment
    name: dws-webhook
    namespace: dws-system
  patch: |-
    kind: Deployment
    metadata:
      name: dws-webhook
      annotations:
        argocd.argoproj.io/sync-options: Replace=true,PruneLast=false,Force=true

