apiVersion: apps/v1
kind: Deployment
metadata:
  name: nnf-dm-manager-controller-manager
  namespace: nnf-dm-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - mountPath: /localdisk/dumps
              name: core-dumps
      volumes:
        - name: core-dumps
          hostPath:
            path: /localdisk/dumps
            type: DirectoryOrCreate
