---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nnf-dm.yaml
#- nnf-dm-prometheus.yaml

components:
- ../components/container-locations
- ../../universal/container-locations
