apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nnf-dm-crds.yaml
- nnf-dm.yaml
#- nnf-dm-prometheus.yaml

components:
- ../components/container-locations
- ../../universal/container-locations

patches:
- path: dm-controller-coredumps.yaml
  target:
    kind: Deployment
    name: nnf-dm-manager-controller-manager
    namespace: nnf-dm-system
- path: dm-manager-coredumps.yaml
  target:
    group: nnf.cray.hpe.com
    kind: NnfDataMovementManager
    name: nnf-dm-manager-controller-manager
    namespace: nnf-dm-system


  # Use images with mpifileutils/mpirun debug symbols
images:
- name: ghcr.io/nearnodeflash/nnf-dm
  newName: ghcr.io/nearnodeflash/nnf-dm-debug
- name: ghcr.io/nearnodeflash/nnf-mfu
  newName: ghcr.io/nearnodeflash/nnf-mfu-debug
